[package]
name = "guessing_game"
version = "0.1.0"
authors = ["moreirajorge_17@outlook.pt"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name="main"
path="./src/main.rs"